spring:
  application:
    name: social-data-service

  datasource:
    url: jdbc:postgresql://social-data-db:5432/social_data_db
    username: social_data_user
    password: social_data_pass
    driver-class-name: org.postgresql.Driver


  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_schema: social

  flyway:
    enabled: true
    schemas: social
    baseline-on-migrate: true
    locations: classpath:db/migration

server:
  port: 8081
